# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=140)),
                ('teacher', models.CharField(max_length=140)),
                ('weekly_count', models.IntegerField()),
                ('is_lab', models.IntegerField()),
                ('year', models.CharField(max_length=140)),
                ('classroom', models.IntegerField()),
                ('units', models.IntegerField()),
            ],
        ),
    ]
