# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161226_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='daily_count',
            field=models.IntegerField(default=1),
        ),
    ]
