# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lecture_daily_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_practical',
            field=models.IntegerField(choices=[(0, 'Lecture_'), (1, 'Practical_')]),
        ),
    ]
