# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170108_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_practical',
            new_name='is_lab',
        ),
    ]
