# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170108_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='location',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
