# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lecture_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_teacher', models.CharField(blank=True, default='', max_length=140)),
                ('tt_subject', models.CharField(blank=True, max_length=140)),
                ('tt_weekly_count', models.IntegerField(blank=True)),
                ('tt_is_lab', models.IntegerField(blank=True, choices=[(0, 'Lecture'), (1, 'Practical')])),
                ('tt_year', models.CharField(blank=True, choices=[('SY_A', 'Second Year: A'), ('SY_B', 'Second Year: B'), ('TY_A', 'Third Year: A'), ('TY_B', 'Third Year: B')], max_length=52)),
                ('tt_location', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_lab',
            field=models.IntegerField(choices=[(0, 'Lecture'), (1, 'Practical')]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='year',
            field=models.CharField(choices=[('SY_A', 'Second Year: A'), ('SY_B', 'Second Year: B'), ('TY_A', 'Third Year: A'), ('TY_B', 'Third Year: B')], max_length=52),
        ),
    ]
