# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170110_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='tt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
