# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_timetable_tt_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshCount',
            fields=[
                ('refresh_count', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='tt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
