# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170204_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshcount',
            name='refresh_count',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
