# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170204_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshcount',
            old_name='refresh_count',
            new_name='id',
        ),
    ]
