# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170204_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshCount',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='tt_id',
        ),
    ]
