# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170204_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshCount',
            fields=[
                ('refresh_count', models.AutoField(primary_key=True, serialize=False)),
                ('tt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='tt_created',
        ),
    ]
