# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170204_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshcount',
            old_name='refresh_count',
            new_name='id',
        ),
        migrations.AddField(
            model_name='refreshcount',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
