# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170204_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='tt_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
